# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI/CD pipeline for dev environment

on:
  push:
    branches: [ dev ]

jobs:
  continuous-integration:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # Step 1 - Check out dev branch of backend application
    - uses: actions/checkout@master
      with:
        repository: NoAgility/personal-crm-backend
        token: ${{ secrets.BACKEND_ACCESS_TOKEN }}
        ref: refs/heads/dev
      # Step 2
    - name: Build and run Backend application
      run: docker-compose --env-file config/dev.env up -d 
  continuous-deployment:
    runs-on: ubuntu-latest
    needs: [continuous-integration]
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1
      # Install NodeJS
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      # Run npm install and build on our code
      - run: npm install
      - run: npm run build --if-present
      - name: 'Deploy to Netlify'
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_DEV }}
        with:
          args: deploy --dir=build --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
