# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI - PR into main branch

on:
  pull_request:
    branches: [ main ]

jobs:
  continuous-integration:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # Step 1 - Check out dev branch of backend application
    - uses: actions/checkout@master
      with:
        repository: NoAgility/personal-crm-backend
        token: ${{ secrets.BACKEND_ACCESS_TOKEN }}
        ref: refs/heads/dev
    # Step 2 - Set up JDK
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
      # Step 3
    - name: Build and run Backend application
      env:
        ENV: local
      run: mvn -B package --file backend-service/backend-service-app/pom.xml
      
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Build and run React JS application
      env:
        BACKEND_IP_ADDRESS: 'localhost:8080'
      run: npm run build --if-present
    - name: Run integration and unit tests - React
      env:
        BACKEND_IP_ADDRESS: 'localhost:8080'
      run: npm test
